<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/jquery.fancybox.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/perfect-scrollbar.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/responsive.css') }}">
<link rel="stylesheet" href="{{ asset('assets/front/blubuild/css/color.css') }}">